version: '3'
services:
  rvc-voice-changer:
    image: shoot2033/rvc-voice-changer:latest
    build: .
    ports:
      - "7860:7860"  # Gradio is bound to port 7860
      - "5000:5000"  # Flask is bound to port 5000
    volumes:
      - .:/rvc-docker
      - weights:/models
      - ./files:/rvc-docker/files  # Mount local files directory to container
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rq-worker-pool:
    image: shoot2033/rq-worker-pool:latest
    build:
      context: .
      dockerfile: Dockerfile_worker_pool
    volumes:
      - .:/worker-pool-docker
      - ./files:/worker-pool-docker/files  # Mount local files directory to container
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

volumes:
  weights:
    driver: local
  files:
    driver: local