FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime

FROM python:3.10.14

# Downgrade pip to a version that doesn't cause conflicts
RUN pip install pip==24.0

# Install system dependencies
RUN apt-get update && apt-get install -y \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /worker-pool-docker

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117


# Now copy the project files
COPY . /worker-pool-docker

RUN mkdir -p /worker-pool-docker/files

# Expose the port the app will run on
COPY . .

# Define the command to run your app
CMD rq worker --with-scheduler voice_conversion
